### ISSUE TITLE
Tapping on a notification in Notification Center while app in foreground but inactive doesn't return .UserTappedToBringAppToForeground

### ISSUE THREAD

**Issue by NinoScript** [square/SuperDelegate#11] opened 2016-09-07 17:53 UTC
If a notification is received when the app is not in foreground, the app is then launched, notification center is opened and a notification is tapped, the `notificationOrigin` is marked as `.DeliveredWhileInForground`.

I noticed that in that case, the following is true:
`applicationIsInForeground && application.applicationState == .Inactive`

I propose that we look for that case and return `.UserTappedToBringAppToForeground` instead.
Something like this:

```
    let notificationOrigin: UserNotificationOrigin
    if applicationIsInForeground {
        notificationOrigin = application.applicationState == .Inactive
            ? .UserTappedToBringAppToForeground
            : .DeliveredWhileInForground
    } else if application.applicationState == .Background && remoteNotification.contentAvailable {
        notificationOrigin = .DeliveredWhileInBackground
    } else {
        notificationOrigin = .UserTappedToBringAppToForeground
    }
```

**Comment by dfed** [comment] 2016-09-07 21:56
Fun bug! What iOS version are you running?

I think this is a bug in our tracking of `applicationIsInForeground`. It should never be `true` when `application.applicationState == .Inactive`

**Comment by NinoScript** [comment] 2016-09-12 13:25
Tested on an iPhone 5S with iOS 9.3.2

**Comment by dfed** [comment] 2016-09-13 00:12
Can you reproduce this in SampleDelegate? Does it only reproduce in the simulator, or does it reproduce on device too?

Thus far I'm unable to reproduce in SampleDelegate in the simulator. Curious to see if your experience is different from mine.

**Comment by dfed** [comment] 2016-09-13 00:22
To make things easy, here's the patch to SampleDelegate I was using to test: [11-test-patch.txt](https://github.com/square/SuperDelegate/files/468593/11-test-patch.txt)

Was breaking inside `didReceiveLocalNotification` and printing `notificationOrigin` in the debugger.

**Comment by radex** [comment] 2016-09-13 21:46
This might be tricky though because if you only differentiate by `application.applicationState == .Inactive` to treat a notification as "user tapped to bring to foreground", you'll have another bug: if a notification is delivered while a user is in the app switcher, the notification action will be triggered!

I'm interested to see how you resolve this (without iOS 10-only APIs, that is), because I have been unable to do so in my app. I could fix the app switcher bug by only only accepting notifications when `.Inactive` if app is "transitioning to foreground" (that is, between willEnterForeground and didBecomeActive). But that's precisely what causes opening from NC to fail, because in this case, the app does not pass the "transitioning to foreground" heuristic.

**Comment by dfed** [comment] 2016-09-13 23:10
In the process of writing this comment I came to understand the issue that @NinoScript is hitting and am now able to reproduce it. Shoot.

We solve the problem @radex mentions via [how we track](https://github.com/square/SuperDelegate/blob/0.8.2/Sources/SuperDelegate.swift#L80) `applicationIsInForeground`. Basically we consider ourselves in the foreground between getting `UIApplicationDidBecomeActiveNotification` and `UIApplicationDidEnterBackgroundNotification`, which does solve the "transitioning to foreground" heuristic.

We can't trust `UIApplicationWillResignActiveNotification` for a bunch of reasons: it can happen due to Touch ID, task switcher, pulling control center up, etc.. I think being wrong in this particular case is better than being wrong in all the above cases.

I'm not sure we can come up with a fix for iOS 8 and 9. I'm hoping with the new `UserNotifications` framework we can solve this in iOS 10. Per #3 I plan on adopting this API in the near future (and in a way that'll be compatible across iOS 8, 9 and 10 with a single client-side implementation).

If anyone out in the community has ideas on how to solve this on iOS 8 and 9, I'd happily hear them!

**Comment by radex** [comment] 2016-09-14 08:08
@dfed Interesting! Thanks for sharing this.

**Comment by dfed** [comment] 2017-01-26 22:21
This will be fixed by adopting the iOS 10 API. As far as I have been able to tell there's no way to fix this with legacy API. Closing this out.

**Closed by dfed** 2017-01-26 22:21 UTC
Labels: bug, help wanted
